export const MAX_COMPANY_LINKS = 8;

export const MAX_COMPANY_BANNERS = 3;

export const LIMITS = {
  FREE: {
    MAX_CATEGORIES: 5,
    MAX_PRODUCTS: 10,
    MAX_IMAGES_PER_PRODUCT: 3,
    MAX_CONTACT_LINKS: 2,
  },
  PREMIUM: {
    MAX_IMAGES_PER_PRODUCT: 5,
    MAX_CONTACT_LINKS: 10,
    MAX_BANNERS: 3,
  },
};
