export const LIMITS = {
  FREE: {
    MAX_CATEGORIES: 5,
    MAX_PRODUCTS: 10,
    MAX_IMAGES_PER_PRODUCT: 3,
    MAX_VARIATIONS_PER_PRODUCT: 1,
    MAX_OPTIONS_PER_VARIATION: 10,
    MAX_CONTACT_LINKS: 2,
  },
  PREMIUM: {
    MAX_IMAGES_PER_PRODUCT: 5,
    MAX_VARIATIONS_PER_PRODUCT: 2,
    MAX_OPTIONS_PER_VARIATION: 10,
    MAX_CONTACT_LINKS: 10,
    MAX_LINKS_PAGE_LINKS: 10,
    MAX_BANNERS: 3,
  },
};
